### ISSUE TITLE
Skip links issue

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/web-design-2-independent-project#14]
Hi! I keep getting a weird message from markbot telling me that skip links should be the first child even when it is along with it should be linking to the right content...
<img width="504" alt="Screen Shot 2021-12-13 at 3 42 07 PM" src="https://user-images.githubusercontent.com/74632728/145887205-6d0059b5-3503-48a2-bf85-2ef7cde7379d.png">
 
@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Try renaming the class for your skip links to match. you currently have it as `skiplinks` but markbot is looking for `skip-links`

You will also need to update the css when you rename the class

**Comment by askaalyy** [comment]
omg how did I miss that... Thank you!
